/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.iupp;

import org.junit.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
